### ISSUE TITLE
go-librespot master - failed creating new session 

### ISSUE THREAD

**Issue by szygmunt** [devgianlu/go-librespot#132] opened 2024-10-29 19:56 UTC
I would like to test some improvements since last stable v0.1 but can't connect to go-librespot from my android app with error:

`ERRO[0025] failed creating new session for xxx from yyy  error="failed obtaining client token: invalid status code from clienttoken: 400"
INFO[0025] refused zeroconf user xxx from yyy`

I'm using config which i can connect to v0.1 with no problem.

**Comment by devgianlu** [comment] 2024-11-02 17:40
I have just tested this but I was not able to reproduce. Are you still affected?

**Comment by szygmunt** [comment] 2024-11-02 20:26
Yes, i'm still affected. Tried "zeroconf" and "interactive" credentials and result is the same:
`error="failed obtaining client token: invalid status code from clienttoken: 400"`

**Comment by devgianlu** [comment] 2024-11-03 12:57
I have identified a possible issue and fixed it with https://github.com/devgianlu/go-librespot/commit/c77366d2e8a3ff930abe74306c1a5650c2fa45f4. I still cannot reproduce, but I hope this fix does with v0.1.1 (to be released).

**Comment by szygmunt** [comment] 2024-11-03 20:01
For clarify: are you talking about MASTER prebuilt binaries downloaded from github "Actions" section? I have no problem with last v0.1 but prebuilt master bin for armv6_rpi is still affected even after your last update (c77366d).

**Comment by devgianlu** [comment] 2024-11-04 11:36
Oh, I didn't understand that it was the development builds! Fixed now.

**Closed by devgianlu** 2024-11-04 11:36 UTC
Labels: bug
