### ISSUE TITLE
Gapless not working 

### ISSUE THREAD

**Issue by volumio** [devgianlu/go-librespot#45] opened 2024-06-05 08:38 UTC
Even when implementing gapless on Volumio, it's not working as there's a slight pause in playback. Try with the Pink Floyd album the dark side of the moon, the transition from track 1 to 2 shall be smooth.

Use https://github.com/volumio/volumio-plugins-sources/tree/spotify14

**Comment by tylkie** [comment] 2024-06-06 10:58
According to https://en.wikipedia.org/wiki/Gapless_playback this will be quite some work to fix, especially without real-time scheduling. A timing granularity of 1ms won't suffice to eliminate conceivable gaps. This is not a bug, but a feature, I believe.

**Comment by devgianlu** [comment] 2024-06-06 11:06
I feel like there's still some improvements that can be made because the output driver will wait for the alsa sink to drain and then start the playback of the next track. I think an optimization can be made by not draining and simply letting the frames go through immediately after, but I haven't investigated this yet. This is why I marked it as a bug.

**Comment by tylkie** [comment] 2024-06-06 14:36
I really hope you're right. I would guess that switching audio source will always impose the risk of micro-latencies.

**Comment by tylkie** [comment] 2024-06-07 19:40
I just tried your assumption. I removed the following lines from `driver_unix.go`

`203: out.cond.L.Lock()`
`204: C.snd_pcm_drain(out.pcmHandle)`
`205: out.cond.L.Unlock()`

To my available sense of hearing, the transition is gapless after that. Unfortunately the last frames of the first song get cut off... so no smooth transition either.

[https://stackoverflow.com/questions/3936420/alsa-how-to-tell-when-a-sound-is-finished-playing](url)

Following this post, draining probably is the source of latency between streams. I fiddled around a bit with pcm_delay in order to get a better timing without the overhead from pcm_drain, but without any luck so far. I'd really love to get deeper into this, but unfortunately I don't have the time for this at the moment... my queue is quite filled up, too... :-/

The linux community has moved from direct communication with the alsa kernel driver to more application layer friendly solutions for mixing streams from different sources... such as PulseAudio and PipeWire. This would have some more advantages... like not having the player block the alsa sink for other applications and users on the same system. Stream mixing (i.e. crossfade) and stream manipulation (i.e. an equalizer) would be much easier, too.

**Comment by devgianlu** [comment] 2024-07-10 08:37
I have started implementing an alternative solution to `pcm_drain` in [gapless](https://github.com/devgianlu/go-librespot/tree/gapless). Like I mentioned in the commit, it works for sequential playback, but it breaks very easily. It's a start, lets see where it goes.

**Closed** 2024-07-25 07:30 UTC
Labels: bug
