### ISSUE TITLE
Reordering of queue has unexpected behaviours

### ISSUE THREAD

**Issue by devgianlu** [devgianlu/go-librespot#73] opened 2024-08-21 07:52 UTC
Android: reordering tracks will duplicate the track being moved
iPhone: https://community.volumio.com/t/new-2023-spotify-plugin/63381/362

**Comment by aykevl** [comment] 2024-10-04 09:35
I debugged this a bit.

The issue appears to be that added tracks need an uid to make things like reordering work correctly. Adding an uid fixes this.

Interestingly a similar bug is present when transferring between the Android app and open.spotify.com: if you add a few songs to the queue, then transfer to a different device, and then add some more songs, the queue now has multiple queued tracks of the same uid because the new device started counting from 0 again. That will really mess up the queue when you try to reorder these songs.
This is clearly a Spotify bug though. I'd say we can do better :)

**Comment by aykevl** [comment] 2024-10-04 20:25
The same issue is present when transferring from Spotify Android to the desktop app (on MacOS). The UIDs start counting again from 0, and reordering the queue messes up the whole queue. So this issue seems really widespread among Spotify apps.

**Comment by devgianlu** [comment] 2024-10-04 20:44
I wonder if this is somehow related to #54

**Comment by aykevl** [comment] 2024-10-04 20:53
Yeah I was thinking the same. We can fix this bug and see if that helps.

I'll probably send a PR tomorrow.

**Comment by justinerickson** [comment] 2024-10-04 21:32
Interesting, is there an easy way to see the UIDs assigned?

I'm particularly curious to see if I can check how they look when playing on Echo/Alexa or Google Home as so far they seem to be stable with multiple devices adding to the same Spotify Jam and reordering the play queue. Though unsure if I'm getting lucky or they're doing something different. I am using Spotify MacOS and iPhone mostly but also didn't see issue with a quick test with open.spotify.com (but was just a quick test). Btw in case helpful Spotify Jam seemed to work well prior to the new plug-in (ie with volspotconnect2) though unsure if Spotify API changed since then.

Let me know if there is anything I can help capture/test to diagnose and/or see if the new PR tomorrow runs into other issues.

**Comment by aykevl** [comment] 2024-10-05 09:04
> Interesting, is there an easy way to see the UIDs assigned?

The way I did it is by opening Developer Tools (Firefox) of open.spotify.com, and in the network tab filtering for WebSocket connections (you will need to reload the page for it to become visible). If you select the one WebSocket connection and go to the Response tab, you can see all the messages exchanged. One of the more frequent messages you see is a cluster update, which contains `payloads[0].cluster.player_state.next_tracks`.
The same probably also works in Chrome.

Note that the API is different between the desktop app and open.spotify.com, but the player state appears to be the same data structure.



> I'm particularly curious to see if I can check how they look when playing on Echo/Alexa or Google Home as so far they seem to be stable with multiple devices adding to the same Spotify Jam and reordering the play queue.

I would be very curious about that!
I'm not using Spotify Jam, just normal "connect to a different device". I guess Spotify Jam might work differently?

**Comment by aykevl** [comment] 2024-10-05 10:15
Fixed here: https://github.com/devgianlu/go-librespot/pull/114

By the way, to reproduce the reordering issue among official Spotify apps (controlled from Spotify Android):

* clear the queue
* switch to a different device
* add a track to the queue
* switch to a different device (could be the first again)
* add a different track to the queue
* reorder the tracks

You may have to do the last step more than once to see the bug. The bug is that after a reorder, both tracks in the queue are now the same (in fact, if you select one, the other will be selected as well at the same time).

**Comment by justinerickson** [comment] 2024-10-05 20:01
I tried combos of adding songs, reordering, finishing songs to dequeue, across Spotify MacOS, Spotify iOS, and open.spotify.com playing on my Echo Dot. It is able to successfully keep monotonically increasing the UID.

It is able to do so even when I reorder such that we dequeue the highest uid (as well as finish playing the previously dequeued highest uid. I'm unsure where it preserves the highest uid as I don't see it anywhere in the payloads JSON. I can see that Spotify is keeping my Recently Played songs in the Spotify MacOS app though

Here is my specific set of steps (and checks I did to confirm it works with Echo Dot). I also attached the final state of next_tracks JSON values
**[next_tracks_json.txt](https://github.com/user-attachments/files/17267328/next_tracks_json.txt)**

**Steps taken**
1. Set all to play on Echo Dot (without Spotify Jam)
2. Added songs to queue from Spotify MacOS, iOS, and [open.spotify.com](http://open.spotify.com/)
3. Check: Correctly number with unique UIDs prior to reordering across all 3 devices
4. Shuffle songs on multiple devices in random orders
5. Check: preserves original unique UIDs in new ordering
6. Finish current song (causes q3 to queue)
7. Add a new song from Spotify MacOS, iOS, and open.spotify.com
8. Check: New song is added as q10, q11, q12 (kept q3 unused)
9. Put q12 (highest number as next in queue) and q1 at end of queue
10. Finished current song so q12 starts playing
11. Check: New song added as q13 (see current track preserves uid: “q12”)
12. Put q13 as next song
13. Finish playing q12 and q13 (current song is now q6)
14. Add new song from iOS app
15. Check: New song added as q14 (unsure how??)
16. Moved q14 top of queue and finish current and q14
17. Add new song from [open.spotify.com](http://open.spotify.com/)
18. Check: New song added as q15 (still unsure how??)
19. Captured ending state below

**uids to device mapping**
Just added songs prior to shuffling
q0 = Spotify MacOS
q1 = Spotify iOS
q2 = Spotify iOS
q3 = [open.spotify.com](http://open.spotify.com/)
a4 = Spotify MacOS
q5 = [open.spotify.com](http://open.spotify.com/)
q6 = [open.spotify.com](http://open.spotify.com/)

Added after shuffling
q7 = Spotify MacOS
q8 = Spotify iOS
q9 = [open.spotify.com](http://open.spotify.com/)

After song finishes & q3 becomes current song
q10 = Spotify MacOS
q11 = [open.spotify.com](http://open.spotify.com/)
q12 = Spotify iOS

After making the highest number song finish playing (not just dequeue)
q13 = Spotify MacOS
q14 = Spotify iOS
q15 = [open.spotify.com](http://open.spotify.com/)

**Comment by justinerickson** [comment] 2024-10-05 20:53
Ahh I missed where you said switch to a different device for playing after reordering, above was all on same playing device. I do see the bug where Spotify resets uid to "q0" after each playing device switch.

Here is what I see when I switch devices (between Echo Dot, Google Home, and Spotify MacOS):
* Each time I switch device, any newly added items in queue start at "q0" again causing duplicates
* Queue seems to play just fine and items don't disappear like what I was seeing with Volumio
* Reordering still works (though janky UI if you are watching the queue per next point)
* Spotify UI falls temporarily out of sync when reordering or new song plays with duplicate uid (close / reopen queue panel seems to fix this)

Attached is next_tracks JSON after switching between devices a few times and adding songs in between. Then reodering and playing one of the uid:"q0" songs.
[next_tracks_swapdevices_json.txt](https://github.com/user-attachments/files/17267433/next_tracks_swapdevices_json.txt)

Seems like an oversight and simple bug where each device should just set the uid to the max uid of the next_tracks objects (possibly max of next_tracks uid's + current song uid)

Note: The bug I was seeing with Volumio that reordering from multiple devices was causing items to disappear even when playing on the single Volumio device the entire time.

**Comment by aykevl** [comment] 2024-10-05 21:44
@justinerickson thank you for the in-depth testing! Then it really looks like a Spotify bug here, that we can only work around.

One other option would be to assign random UIDs, I tried this and it works but figured that keeping the pattern of q0, q1, etc might be better for compatibility.

**Comment by justinerickson** [comment] 2024-10-05 21:59
No problem and agreed your PR looks like the best workaround for swapping playing devices.

For the original issue where attempting to reorder songs that were added to a Volumio queue (without changing playing device) was causing them to disappear is a symptom of not setting "uid"? If so, this hopefully that fixes the other  issues I was seeing with the queue disappearing periodically when trying to use multiple Spotify apps to add songs to the same Volumio playing device queue.

**Closed** 2024-10-06 06:28 UTC
Labels: bug

**Comment by justinerickson** [comment] 2024-10-21 19:28
FYI I manually updated my setup with this fix and from initial testing so far seems to fix all the multi-user Spotify Jams/enqueuing issues. Will post if any new surprises. Thanks for the fix (and pointers on how to inspect the Spotify payloads)!!!

**Comment by pachulo** [comment] 2025-02-02 09:59
Hi! I am still experiencing weird behaviour when reordering tracks on the queue from the Android's Spotify app: it seems like the changes of order are ignored. 

 Thanks for all the work involved!
